# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /auto/bunter_usr5/nestorj/life_prototype/lp1/lp1.cache/wt [current_project]
set_property parent.project_path /auto/bunter_usr5/nestorj/life_prototype/lp1/lp1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog /auto/bunter_usr5/nestorj/life_prototype/pe_decs.sv
set_property file_type "Verilog Header" [get_files /auto/bunter_usr5/nestorj/life_prototype/pe_decs.sv]
set_property is_global_include true [get_files /auto/bunter_usr5/nestorj/life_prototype/pe_decs.sv]
read_verilog -library xil_defaultlib -sv {
  /auto/bunter_usr5/nestorj/life_prototype/pe_array_decs.sv
  /auto/bunter_usr5/nestorj/life_prototype/pe.sv
  /auto/bunter_usr5/nestorj/life_prototype/pe_array.sv
}
synth_design -top pe_array -part xc7vx485tffg1157-1
write_checkpoint -noxdef pe_array.dcp
catch { report_utilization -file pe_array_utilization_synth.rpt -pb pe_array_utilization_synth.pb }
