set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN Y9 [get_ports clk]
create_clock -period 10 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports red]
set_property IOSTANDARD LVCMOS33 [get_ports green]
set_property IOSTANDARD LVCMOS33 [get_ports blue]
set_property IOSTANDARD LVCMOS33 [get_ports Hsync]
set_property IOSTANDARD LVCMOS33 [get_ports Vsync]
set_property IOSTANDARD LVCMOS33 [get_ports leds]

set_property IOSTANDARD LVCMOS25 [get_ports debug]
set_property IOSTANDARD LVCMOS25 [get_ports enb]
set_property IOSTANDARD LVCMOS25 [get_ports reset]

set_property PACKAGE_PIN V20 [get_ports {red[3]}]
set_property PACKAGE_PIN U20 [get_ports {red[2]}]
set_property PACKAGE_PIN V19 [get_ports {red[1]}]
set_property PACKAGE_PIN V18 [get_ports {red[0]}]
set_property PACKAGE_PIN AB22 [get_ports {green[3]}]
set_property PACKAGE_PIN AA22 [get_ports {green[2]}]
set_property PACKAGE_PIN AB21 [get_ports {green[1]}]
set_property PACKAGE_PIN AA21 [get_ports {green[0]}]
set_property PACKAGE_PIN Y21 [get_ports {blue[3]}]
set_property PACKAGE_PIN Y20 [get_ports {blue[2]}]
set_property PACKAGE_PIN AB20 [get_ports {blue[1]}]
set_property PACKAGE_PIN AB19 [get_ports {blue[0]}]

set_property PACKAGE_PIN AA19 [get_ports {Hsync}]
set_property PACKAGE_PIN Y19 [get_ports {Vsync}]

set_property PACKAGE_PIN H19 [get_ports {debug}]
set_property PACKAGE_PIN F22 [get_ports {enb}]
set_property PACKAGE_PIN P16 [get_ports {reset}]

set_property PACKAGE_PIN U14 [get_ports {leds[3]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]
set_property PACKAGE_PIN T21 [get_ports {leds[1]}]
set_property PACKAGE_PIN T22 [get_ports {leds[0]}]
